const express=require('express');const path=require('path');const fs=require('fs');const helmet=require('helmet');const bcrypt=require('bcryptjs');const jwt=require('jsonwebtoken');const multer=require('multer');const XLSX=require('xlsx');const db=require('./db');
const app=express(),PORT=process.env.PORT||3000,ROOT=path.join(__dirname,'..'),JWT_SECRET=process.env.JWT_SECRET||'CHANGE_THIS_IN_PRODUCTION',ADMIN_KEY=process.env.ADMIN_KEY||'';
app.use(helmet({contentSecurityPolicy:false}));app.use(express.json({limit:'2mb'}));app.use(express.urlencoded({extended:true}));
const uploadDir=path.join(ROOT,'uploads','counselor');fs.mkdirSync(uploadDir,{recursive:true});const upload=multer({dest:uploadDir,limits:{fileSize:10*1024*1024}});
function nationalIdValid(code){if(!/^\d{10}$/.test(code)||/^(\d)\1{9}$/.test(code))return false;let s=0;for(let i=0;i<9;i++)s+=Number(code[i])*(10-i);const r=s%11;return r<2?Number(code[9])===r:Number(code[9])===11-r}
function seed(){if(db.prepare('SELECT COUNT(*) c FROM students').get().c)return;const hash=bcrypt.hashSync('123456',12);const st=db.prepare('INSERT INTO students(national_id,password_hash,first_name,last_name,grade,field,class_name) VALUES(?,?,?,?,?,?,?)').run('1000000001',hash,'محمدرضا','احمدی','دهم','علوم انسانی','۱۰۲');const insC=db.prepare('INSERT INTO classes(title,teacher,weekday,time) VALUES(?,?,?,?)');const cls=[['ریاضی','استاد علوی','شنبه','۸:۰۰'],['فارسی','استاد محمدی','شنبه','۱۰:۰۰'],['عربی','استاد کریمی','یکشنبه','۸:۰۰'],['اقتصاد','استاد احمدی','یکشنبه','۱۰:۰۰']].map(x=>insC.run(...x).lastInsertRowid);const en=db.prepare('INSERT INTO enrollments(student_id,class_id) VALUES(?,?)');cls.forEach(id=>en.run(st.lastInsertRowid,id));const g=db.prepare('INSERT INTO grades(student_id,subject,score,term) VALUES(?,?,?,?)');[['ریاضی',19.5,'نوبت اول'],['فارسی',19,'نوبت اول'],['عربی',19.25,'نوبت اول'],['اقتصاد',19.3,'نوبت اول']].forEach(x=>g.run(st.lastInsertRowid,...x));const c=db.prepare('INSERT INTO consents(student_id,title,status,updated_at) VALUES(?,?,?,?)');c.run(st.lastInsertRowid,'رضایت‌نامه اردوی علمی','pending','');c.run(st.lastInsertRowid,'رضایت‌نامه برنامه فرهنگی','done',new Date().toISOString());db.prepare('INSERT INTO announcements(title,body,audience,created_at) VALUES(?,?,?,?)').run('آغاز سال تحصیلی','اطلاعیه‌های اختصاصی دانش‌آموزان از این بخش نمایش داده می‌شود.','all',new Date().toISOString());db.prepare('INSERT INTO exams(student_id,subject,exam_date) VALUES(?,?,?)').run(st.lastInsertRowid,'ریاضی','۱۴۰۵/۰۶/۱۲')}
seed();
function auth(req,res,next){const t=req.headers.authorization?.replace(/^Bearer\s+/,'');if(!t)return res.status(401).json({error:'unauthorized'});try{req.user=jwt.verify(t,JWT_SECRET);next()}catch{return res.status(401).json({error:'unauthorized'})}}
app.post('/api/auth/login',(req,res)=>{const {nationalId,password}=req.body||{};if(!nationalIdValid(String(nationalId||'')))return res.status(400).json({error:'کد ملی معتبر نیست'});const st=db.prepare('SELECT * FROM students WHERE national_id=?').get(String(nationalId));if(!st||!bcrypt.compareSync(String(password||''),st.password_hash))return res.status(401).json({error:'کد ملی یا رمز عبور نادرست است'});res.json({token:jwt.sign({id:st.id,role:'student'},JWT_SECRET,{expiresIn:'8h'})})});
app.get('/api/student/dashboard',auth,(req,res)=>{if(req.user.role!=='student')return res.status(403).json({error:'forbidden'});const st=db.prepare('SELECT id,first_name,last_name,grade,field,class_name,photo FROM students WHERE id=?').get(req.user.id);if(!st)return res.status(404).json({error:'student_not_found'});const classes=db.prepare('SELECT c.title,c.teacher,c.weekday,c.time,c.online_url FROM classes c JOIN enrollments e ON e.class_id=c.id WHERE e.student_id=? ORDER BY c.id').all(st.id);const grades=db.prepare('SELECT subject,score,term FROM grades WHERE student_id=? ORDER BY id DESC').all(st.id);const consents=db.prepare('SELECT title,status,updated_at FROM consents WHERE student_id=? ORDER BY id DESC').all(st.id);const exams=db.prepare('SELECT subject,exam_date FROM exams WHERE student_id=? ORDER BY exam_date').all(st.id);const announcements=db.prepare("SELECT title,body,created_at FROM announcements WHERE audience='all' OR audience=? ORDER BY id DESC LIMIT 10").all('grade:'+st.grade);const avg=grades.length?grades.reduce((a,g)=>a+g.score,0)/grades.length:0;const classStudents=db.prepare('SELECT id FROM students WHERE class_name=?').all(st.class_name);const classIds=classStudents.map(x=>x.id);let rank=0,classAverage=0;if(classIds.length){const rows=db.prepare(`SELECT student_id,AVG(score) avg FROM grades WHERE student_id IN (${classIds.map(()=>'?').join(',')}) GROUP BY student_id ORDER BY avg DESC`).all(...classIds);rank=Math.max(1,rows.findIndex(x=>x.student_id===st.id)+1);classAverage=rows.length?Number((rows.reduce((a,x)=>a+x.avg,0)/rows.length).toFixed(2)):0}res.json({student:st,classes,grades,average:Number(avg.toFixed(2)),consents,exams,announcements,rank,classSize:classIds.length,classAverage})});
app.post('/api/feedback',(req,res)=>{const {name,subject,message}=req.body||{};if(!name||!subject||!message)return res.status(400).json({error:'همه فیلدها الزامی است'});db.prepare('INSERT INTO feedback(name,subject,message,created_at) VALUES(?,?,?,?)').run(name,subject,message,new Date().toISOString());res.json({ok:true})});
app.get('/api/occasions/today',(req,res)=>{const today=new Date().toISOString().slice(5,10);const items=db.prepare('SELECT title FROM occasions WHERE substr(date,6,5)=?').all(today);res.json({items})});
function adminAuth(req,res,next){if(!ADMIN_KEY)return res.status(503).json({error:'ADMIN_KEY is not configured'});if(req.headers['x-admin-key']!==ADMIN_KEY)return res.status(401).json({error:'admin_unauthorized'});next()}
app.get('/api/admin/stats',adminAuth,(req,res)=>{res.json({students:db.prepare('SELECT COUNT(*) c FROM students').get().c,classes:db.prepare('SELECT COUNT(*) c FROM classes').get().c,pendingConsents:db.prepare("SELECT COUNT(*) c FROM consents WHERE status='pending'").get().c,feedback:db.prepare('SELECT COUNT(*) c FROM feedback').get().c})});
app.post('/api/admin/import-students',adminAuth,upload.single('file'),(req,res)=>{if(!req.file)return res.status(400).json({error:'فایل ارسال نشده است'});try{const wb=XLSX.readFile(req.file.path);const rows=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:''});const tx=db.transaction(items=>{let imported=0;for(const row of items){const first=String(row['نام']||row.first_name||'').trim(),last=String(row['نام خانوادگی']||row.last_name||'').trim(),nid=String(row['کد ملی']||row.national_id||'').trim().padStart(10,'0'),pw=String(row['رمز عبور']||row.password||'').trim(),grade=String(row['پایه']||row.grade||'').trim(),field=String(row['رشته']||row.field||'').trim(),cls=String(row['کلاس']||row.class_name||'').trim();if(!first||!last||!nationalIdValid(nid)||!pw||!grade)continue;const hash=bcrypt.hashSync(pw,12);db.prepare(`INSERT INTO students(national_id,password_hash,first_name,last_name,grade,field,class_name) VALUES(?,?,?,?,?,?,?) ON CONFLICT(national_id) DO UPDATE SET password_hash=excluded.password_hash,first_name=excluded.first_name,last_name=excluded.last_name,grade=excluded.grade,field=excluded.field,class_name=excluded.class_name`).run(nid,hash,first,last,grade,field,cls);imported++}return imported});const imported=tx(rows);fs.unlinkSync(req.file.path);res.json({imported})}catch(e){try{fs.unlinkSync(req.file.path)}catch{}res.status(400).json({error:'فایل Excel قابل پردازش نیست'})}});
app.post('/api/counselor/audio',adminAuth,upload.single('file'),(req,res)=>{if(!req.file)return res.status(400).json({error:'فایل صوتی ارسال نشده است'});const ext=path.extname(req.file.originalname)||'.mp3',dest=path.join(uploadDir,'latest'+ext);try{fs.renameSync(req.file.path,dest);res.json({ok:true,url:'/uploads/counselor/'+path.basename(dest)})}catch{res.status(500).json({error:'ذخیره فایل ناموفق بود'})}});
app.use(express.static(ROOT));app.use((req,res,next)=>{if(req.method==='GET'&&!req.path.startsWith('/api/'))return res.sendFile(path.join(ROOT,'index.html'));next()});app.listen(PORT,()=>console.log(`Shooshtar Sampad V2 on http://localhost:${PORT}`));