const json=(data,status=200,headers={})=>new Response(JSON.stringify(data),{status,headers:{"content-type":"application/json; charset=utf-8",...headers}});
function originHeaders(request,env){const origin=request.headers.get("Origin")||"*";const allowed=env.ALLOWED_ORIGIN||"*";return {"Access-Control-Allow-Origin":allowed==="*"?"*":origin===allowed?origin:allowed,"Access-Control-Allow-Headers":"Content-Type, Authorization, X-Admin-Key","Access-Control-Allow-Methods":"GET,POST,OPTIONS","Vary":"Origin"}}
function b64u(a){return btoa(String.fromCharCode(...new Uint8Array(a))).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"")}
function unb64(s){s=s.replace(/-/g,"+").replace(/_/g,"/");while(s.length%4)s+="=";return Uint8Array.from(atob(s),c=>c.charCodeAt(0))}
async function hmac(secret,text){const key=await crypto.subtle.importKey("raw",new TextEncoder().encode(secret),{name:"HMAC",hash:"SHA-256"},false,["sign"]);return b64u(await crypto.subtle.sign("HMAC",key,new TextEncoder().encode(text)))}
async function token(payload,secret){const head=b64u(new TextEncoder().encode(JSON.stringify({alg:"HS256",typ:"JWT"})));const body=b64u(new TextEncoder().encode(JSON.stringify(payload)));const sig=await hmac(secret,head+"."+body);return head+"."+body+"."+sig}
async function verifyToken(t,secret){try{const [h,p,s]=String(t||"").split(".");if(!h||!p||!s)return null;const good=await hmac(secret,h+"."+p);if(good!==s)return null;const data=JSON.parse(new TextDecoder().decode(unb64(p)));if(data.exp&&Date.now()/1000>data.exp)return null;return data}catch{return null}}
function validNationalId(code){if(!/^\d{10}$/.test(code)||/^(\d)\1{9}$/.test(code))return false;let s=0;for(let i=0;i<9;i++)s+=Number(code[i])*(10-i);const r=s%11;return r<2?Number(code[9])===r:Number(code[9])===11-r}
function csvRows(text){const lines=text.replace(/^\uFEFF/,"").split(/\r?\n/).filter(x=>x.trim());if(!lines.length)return[];const parse=line=>{let a=[],cur="",q=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'&&line[i+1]==='"'){cur+='"';i++;continue}if(c==='"'){q=!q;continue}if(c===','&&!q){a.push(cur.trim());cur=""}else cur+=c}a.push(cur.trim());return a};const heads=parse(lines[0]).map(x=>x.trim());return lines.slice(1).map(line=>{const vals=parse(line);const o={};heads.forEach((h,i)=>o[h]=vals[i]??"");return o})}
async function derive(password,salt){const key=await crypto.subtle.importKey("raw",new TextEncoder().encode(password),"PBKDF2",false,["deriveBits"]);const bits=await crypto.subtle.deriveBits({name:"PBKDF2",salt:new TextEncoder().encode(salt),iterations:120000,hash:"SHA-256"},key,256);return b64u(bits)}
async function hashPassword(password){const salt=crypto.randomUUID();return salt+"."+await derive(password,salt)}
async function checkPassword(password,stored){const [salt,hash]=String(stored||"").split(".");return !!salt&&!!hash&&(await derive(password,salt))===hash}
function now(){return new Date().toISOString()}
async function studentAuth(request,env){const h=request.headers.get("Authorization")||"";const t=h.replace(/^Bearer\s+/i,"");return await verifyToken(t,env.JWT_SECRET)}
export default {async fetch(request,env){const cors=originHeaders(request,env);if(request.method==="OPTIONS")return new Response(null,{status:204,headers:cors});const url=new URL(request.url);try{
if(url.pathname==="/api/health")return json({ok:true,service:"shooshtar-sampad",time:now()},200,cors);
if(url.pathname==="/api/auth/login"&&request.method==="POST"){const body=await request.json();const nid=String(body.nationalId||"").trim();if(!validNationalId(nid))return json({error:"کد ملی معتبر نیست."},400,cors);const st=await env.DB.prepare("SELECT id,first_name,last_name FROM students WHERE national_id=?").bind(nid).first();if(!st)return json({error:"دانش‌آموز با این کد ملی پیدا نشد."},404,cors);const t=await token({sub:String(st.id),role:"student",exp:Math.floor(Date.now()/1000)+8*60*60},env.JWT_SECRET);return json({token:t},200,cors)}
if(url.pathname==="/api/student/dashboard"&&request.method==="GET"){const u=await studentAuth(request,env);if(!u||u.role!=="student")return json({error:"نشست معتبر نیست."},401,cors);const s=await env.DB.prepare("SELECT id,national_id,first_name,last_name,grade,field,class_name,photo FROM students WHERE id=?").bind(u.sub).first();if(!s)return json({error:"student_not_found"},404,cors);const classes=(await env.DB.prepare("SELECT c.title,c.teacher,c.weekday,c.time,c.online_url FROM classes c JOIN enrollments e ON e.class_id=c.id WHERE e.student_id=? ORDER BY c.id").bind(s.id).all()).results||[];const grades=(await env.DB.prepare("SELECT subject,score,term FROM grades WHERE student_id=? ORDER BY id DESC").bind(s.id).all()).results||[];const consents=(await env.DB.prepare("SELECT title,status,updated_at FROM consents WHERE student_id=? ORDER BY id DESC").bind(s.id).all()).results||[];const exams=(await env.DB.prepare("SELECT subject,exam_date FROM exams WHERE student_id=? ORDER BY exam_date").bind(s.id).all()).results||[];const announcements=(await env.DB.prepare("SELECT title,body,created_at FROM announcements WHERE audience='all' OR audience=? ORDER BY id DESC LIMIT 10").bind("grade:"+String(s.grade||"")).all()).results||[];const files=(await env.DB.prepare("SELECT title,url FROM files WHERE student_id=? ORDER BY id DESC").bind(s.id).all()).results||[];const avg=grades.length?Number((grades.reduce((a,x)=>a+Number(x.score),0)/grades.length).toFixed(2)):0;const peers=(await env.DB.prepare("SELECT s.id,AVG(g.score) avg FROM students s LEFT JOIN grades g ON g.student_id=s.id WHERE s.class_name=? GROUP BY s.id ORDER BY avg DESC, s.id ASC").bind(s.class_name||"").all()).results||[];const rank=Math.max(1,peers.findIndex(x=>String(x.id)===String(s.id))+1);const classAverage=peers.length?Number((peers.reduce((a,x)=>a+Number(x.avg||0),0)/peers.length).toFixed(2)):0;const audio=await env.DB.prepare("SELECT url FROM counselor_audio ORDER BY id DESC LIMIT 1").first();return json({student:s,classes,grades,consents,exams,announcements,files,average:avg,rank,classSize:peers.length,classAverage,counselorAudio:audio?.url||null},200,cors)}
if(url.pathname==="/api/feedback"&&request.method==="POST"){const b=await request.json();const name=String(b.name||"").trim(),subject=String(b.subject||"").trim(),message=String(b.message||"").trim();if(!name||!subject||!message)return json({error:"همه فیلدها الزامی است."},400,cors);await env.DB.prepare("INSERT INTO feedback(name,subject,message,created_at) VALUES(?,?,?,?)").bind(name,subject,message,now()).run();return json({ok:true},200,cors)}
if(url.pathname==="/api/admin/import-students"&&request.method==="POST"){if((request.headers.get("X-Admin-Key")||"")!==env.ADMIN_KEY)return json({error:"کلید مدیریت نادرست است."},401,cors);const fd=await request.formData();const file=fd.get("file");if(!file)return json({error:"فایل CSV ارسال نشده است."},400,cors);const rows=csvRows(await file.text());let imported=0;for(const r of rows){const nid=String(r.national_id||r["کد ملی"]||"").trim();const first=String(r.first_name||r["نام"]||"").trim();const last=String(r.last_name||r["نام خانوادگی"]||"").trim();const grade=String(r.grade||r["پایه"]||"").trim();const field=String(r.field||r["رشته"]||"").trim();const cls=String(r.class_name||r["کلاس"]||"").trim();const password=String(r.password||r["رمز عبور"]||"").trim();if(!validNationalId(nid)||!first||!last||!grade)continue;const hp=password?await hashPassword(password):null;if(hp)await env.DB.prepare("INSERT INTO students(national_id,password_hash,first_name,last_name,grade,field,class_name) VALUES(?,?,?,?,?,?,?) ON CONFLICT(national_id) DO UPDATE SET password_hash=excluded.password_hash,first_name=excluded.first_name,last_name=excluded.last_name,grade=excluded.grade,field=excluded.field,class_name=excluded.class_name").bind(nid,hp,first,last,grade,field,cls).run();else await env.DB.prepare("INSERT INTO students(national_id,first_name,last_name,grade,field,class_name) VALUES(?,?,?,?,?,?) ON CONFLICT(national_id) DO UPDATE SET first_name=excluded.first_name,last_name=excluded.last_name,grade=excluded.grade,field=excluded.field,class_name=excluded.class_name").bind(nid,first,last,grade,field,cls).run();imported++}return json({ok:true,imported},200,cors)}
if(url.pathname==="/api/admin/stats"&&request.method==="GET"){if((request.headers.get("X-Admin-Key")||"")!==env.ADMIN_KEY)return json({error:"کلید مدیریت نادرست است."},401,cors);const students=await env.DB.prepare("SELECT COUNT(*) c FROM students").first();const grades=await env.DB.prepare("SELECT COUNT(*) c FROM grades").first();const feedback=await env.DB.prepare("SELECT COUNT(*) c FROM feedback").first();return json({students:students?.c||0,grades:grades?.c||0,feedback:feedback?.c||0},200,cors)}
return json({error:"not_found"},404,cors)
}catch(e){return json({error:"خطای داخلی سامانه",detail:env.DEBUG?String(e):undefined},500,cors)}}};